# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: avenue magpie
email: saliem@avenuemagpie.net
description:  # this means to ignore newlines until "baseurl:"

 Avenue Magpie, drafted in the mornings is meant to cultivate empathy and joy.
  
 I deconstruct the arts, designs and places to find out what they mean to me and what they mean to others.
  
location: Made with love in San Francisco, California. 
author: Saliem Chiu.
profilephoto: /images/saliem-chiu.jpg
credits: "Avenue Magpie is a collection of art design and travel notes. © Copyright 2018 Saliem Chiu - All rights reserved."

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://avenuemagpie.net" # the base hostname & protocol for your site
twitter_username: saliemchiu
github_username:  

# Build settings
markdown: kramdown
