# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Avenue Magpie
email: saliem@avenuemagpie.net
description: > # this means to ignore newlines until "baseurl:"

  Uncomposed thoughts on art written by Saliem Chiu. Drafted in the mornings and meant to cultivate empathy and joy.
  
  I interpret art, deconstruct it, find out what it means to me, what it means to others.
  
  Made with love in San Francisco, California. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://avenuemagpie.net" # the base hostname & protocol for your site
twitter_username: saliemchiu
github_username:  avenuemagpie

# Build settings
markdown: kramdown
