# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Avenue Magpie
email: saliem@avenuemagpie.net
description: > # this means to ignore newlines until "baseurl:"
  Personal thoughts and reflections on the arts, design and life in San Francisco by Saliem Chiu
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://avenuemagpie.net" # the base hostname & protocol for your site
twitter_username: saliemchiu
github_username:  avenuemagpie

# Build settings
markdown: kramdown
